
version: "3.9"

services:
 mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_USER=app
    - MYSQL_PASSWORD=pass
    - MYSQL_DATABASE=app

 postgres:
    image: postgres:latest
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
    ports:
      - 5432:5432

 emulator:
    build: ./gate-simulator
    ports:
      - '9999:9999'



